
version: '3'

services:
    client:
        image: node:14-alpine
        container_name: client
        build:
            context: .
        restart: unless-stopped
        ports:
            - 5000:5000
        networks:
            - app-network
        working_dir: /home/app/front/
        command: serve -s build

    webserver:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: unless-stopped
        expose: 
            - 8080
        ports:
            - 8080:8080
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - client
        networks:
            - app-network

networks:
    app-network:
        driver: bridge